"""add_virus_scanning_fields

Revision ID: 5812c4e9ec28
Revises: 34d5736c5588
Create Date: 2025-08-05 21:00:01.529903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5812c4e9ec28'
down_revision: Union[str, None] = '34d5736c5588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed celery_tasksetmeta operations - this table is managed by Celery
    op.add_column('files', sa.Column('virus_scan_status', sa.String(length=20), nullable=True))
    op.add_column('files', sa.Column('virus_scan_result', sa.JSON(none_as_null=True), nullable=True))
    op.add_column('files', sa.Column('virus_scan_date', sa.DateTime(), nullable=True))
    op.add_column('files', sa.Column('is_quarantined', sa.Boolean(), nullable=True))
    op.add_column('files', sa.Column('quarantine_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'quarantine_reason')
    op.drop_column('files', 'is_quarantined')
    op.drop_column('files', 'virus_scan_date')
    op.drop_column('files', 'virus_scan_result')
    op.drop_column('files', 'virus_scan_status')
    # Removed celery_tasksetmeta operations - this table is managed by Celery
    # ### end Alembic commands ###
