"""Create initial tables with appointment column

Revision ID: a6fd66b65816
Revises: 6636fe22b643
Create Date: 2025-07-24 22:30:13.939497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fd66b65816'
down_revision: Union[str, None] = '6636fe22b643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('appointment', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_files_appointment'), 'files', ['appointment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_appointment'), table_name='files')
    op.drop_column('files', 'appointment')
    # ### end Alembic commands ###
