"""Add unique upload_id to files table

Revision ID: de84cb899fc5
Revises: a6fd66b65816
Create Date: 2025-07-29 18:03:15.993324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de84cb899fc5'
down_revision: Union[str, None] = 'a6fd66b65816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('upload_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_files_upload_id'), 'files', ['upload_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_upload_id'), table_name='files')
    op.drop_column('files', 'upload_id')
    # ### end Alembic commands ###
