"""keys/fks updates

Revision ID: e1c120d12bbc
Revises: 5812c4e9ec28
Create Date: 2025-08-14 19:41:49.871136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect as sa_inspect
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e1c120d12bbc'
down_revision: Union[str, None] = '5812c4e9ec28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Conditionally drop legacy Celery result-backend table/index if present
    bind = op.get_bind()
    inspector = sa_inspect(bind)

    table_names = set(inspector.get_table_names())
    if 'celery_tasksetmeta' in table_names:
        existing_indexes = {ix.get('name') for ix in inspector.get_indexes('celery_tasksetmeta')}
        if 'taskset_id' in existing_indexes:
            op.drop_index('taskset_id', table_name='celery_tasksetmeta')
        op.drop_table('celery_tasksetmeta')
    op.alter_column('files', 'celery_task_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=True)
    op.create_foreign_key(None, 'files', 'celery_tasks', ['celery_task_id'], ['task_id'])
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=True)
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.alter_column('files', 'celery_task_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.create_table('celery_tasksetmeta',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('taskset_id', mysql.VARCHAR(length=155), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('date_done', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('taskset_id', 'celery_tasksetmeta', ['taskset_id'], unique=True)
    # ### end Alembic commands ###
